apiVersion: batch/v1
kind: Job
metadata:
  name: load-data
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed 
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load-data
        image: mongo:7.0.11
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cred
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cred
              key: password
        command: ["bash"]
        args:
        - -c 
        - |
          apt-get update
          apt-get install curl -y
          curl https://raw.githubusercontent.com/mcampo2/mongodb-sample-databases/master/sample_training/posts.json -o posts.json;
          mongoimport --host {{ .Values.mongoLabel }}.default.svc.cluster.local --port 27017 --db "sample_training" --collection "posts" --file ./posts.json --authenticationDatabase admin -u ${DB_USER} -p ${DB_PASSWORD}  
