apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mongoLabel }}
  name: {{ .Values.mongoLabel }}
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: {{ .Values.mongoLabel }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoLabel }}
  labels:
    app: {{ .Values.mongoLabel }}
spec:
  selector: 
    matchLabels:
      app: {{ .Values.mongoLabel }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mongoLabel }}
      name: {{ .Values.mongoLabel }}
    spec:
      containers:
      - image: mongo:7.0.11
        name: {{ .Values.mongoLabel }}   
        ports:
        - containerPort: 27017
          name: {{ .Values.mongoLabel }}    
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cred
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cred
              key: password
