apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.serverLabel }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.serverLabel }}
    spec:
      containers:
      - name: {{ .Values.serverLabel }}
        image: giuliovn/node-server:latest
        ports:
        - containerPort: 5050
          name: server-port
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cred
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cred
              key: password
        - name: ATLAS_URI
          value: "mongodb://$(DB_USER):$(DB_PASSWORD)@{{ .Values.mongoLabel }}.default.svc.cluster.local"
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverLabel }}
  labels:
    app: {{ .Values.serverLabel }}
spec:
  type: ClusterIP
  selector:
    app: node-server
  ports:
  - name: server
    protocol: TCP
    port: 5050
    targetPort: server-port
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serverLabel }}
            port: 
              number: 5050